/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.4).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package ir.rabbit.group.onlinestore.controller;

import io.swagger.annotations.*;
import ir.rabbit.group.onlinestore.dto.shopping.ShoppingCart;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

import javax.validation.Valid;
import javax.validation.constraints.NotNull;

@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2019-04-26T13:31:08.886Z")

@Api(value = "shoppingCart", description = "the shoppingCart API")
public interface ShoppingCartApi {

    @ApiOperation(value = "add product to the shopping cart", nickname = "addProductByProductId", notes = "", tags = {"shoppingCart",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "successful operation"),
            @ApiResponse(code = 400, message = "Invalid ID supplied"),
            @ApiResponse(code = 404, message = "product not found")})
    @RequestMapping(value = "/shoppingCart/product/",
            produces = {"application/json"},
            method = RequestMethod.GET)
    ResponseEntity<Void> addProductByProductId(@NotNull @ApiParam(value = "productId ", required = true) @Valid @RequestParam(value = "productId", required = true) Long productId, @NotNull @ApiParam(value = "", required = true) @Valid @RequestParam(value = "shoppingCartID", required = true) Long shoppingCartID);


    @ApiOperation(value = "dekete product from the shopping cart", nickname = "deleteProductById", notes = "", tags = {"shoppingCart",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "product deleted from shoppingCart successfully")})
    @RequestMapping(value = "/shoppingCart/product/",
            produces = {"application/json"},
            method = RequestMethod.DELETE)
    ResponseEntity<Void> deleteProductById(@NotNull @ApiParam(value = "productId ", required = true) @Valid @RequestParam(value = "productId", required = true) Long productId, @NotNull @ApiParam(value = "", required = true) @Valid @RequestParam(value = "shoppingCartID", required = true) Long shoppingCartID);


    @ApiOperation(value = "Finds shoppingCart by title", nickname = "findShoppingCartByCustomerId", notes = "", response = ShoppingCart.class, tags = {"shoppingCart",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "successful operation", response = ShoppingCart.class),
            @ApiResponse(code = 400, message = "Invalid id value")})
    @RequestMapping(value = "/shoppingCart/findByCustomerId",
            produces = {"application/json"},
            method = RequestMethod.GET)
    ResponseEntity<ShoppingCart> findShoppingCartByCustomerId(@NotNull @ApiParam(value = "", required = true) @Valid @RequestParam(value = "customerId", required = true) Long customerId);

}
